// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stats.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "stats.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace zproto {

namespace {

const ::google::protobuf::Descriptor* EventRecord_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  EventRecord_reflection_ = NULL;
const ::google::protobuf::Descriptor* Event_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Event_reflection_ = NULL;
const ::google::protobuf::Descriptor* UntypedEvent_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  UntypedEvent_reflection_ = NULL;
const ::google::protobuf::Descriptor* ContentViewChanged_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ContentViewChanged_reflection_ = NULL;
const ::google::protobuf::Descriptor* AppVisibleChanged_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AppVisibleChanged_reflection_ = NULL;
const ::google::protobuf::Descriptor* StoreEventsReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  StoreEventsReq_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_stats_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_stats_2eproto() {
  protobuf_AddDesc_stats_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "stats.proto");
  GOOGLE_CHECK(file != NULL);
  EventRecord_descriptor_ = file->message_type(0);
  static const int EventRecord_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EventRecord, date_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EventRecord, event_),
  };
  EventRecord_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      EventRecord_descriptor_,
      EventRecord::internal_default_instance(),
      EventRecord_offsets_,
      -1,
      -1,
      -1,
      sizeof(EventRecord),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EventRecord, _internal_metadata_));
  Event_descriptor_ = file->message_type(1);
  static const int Event_offsets_[1] = {
  };
  Event_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Event_descriptor_,
      Event::internal_default_instance(),
      Event_offsets_,
      -1,
      -1,
      -1,
      sizeof(Event),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Event, _internal_metadata_));
  UntypedEvent_descriptor_ = file->message_type(2);
  static const int UntypedEvent_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UntypedEvent, event_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UntypedEvent, params_),
  };
  UntypedEvent_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      UntypedEvent_descriptor_,
      UntypedEvent::internal_default_instance(),
      UntypedEvent_offsets_,
      -1,
      -1,
      -1,
      sizeof(UntypedEvent),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UntypedEvent, _internal_metadata_));
  ContentViewChanged_descriptor_ = file->message_type(3);
  static const int ContentViewChanged_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContentViewChanged, content_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContentViewChanged, content_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContentViewChanged, visible_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContentViewChanged, params_),
  };
  ContentViewChanged_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ContentViewChanged_descriptor_,
      ContentViewChanged::internal_default_instance(),
      ContentViewChanged_offsets_,
      -1,
      -1,
      -1,
      sizeof(ContentViewChanged),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContentViewChanged, _internal_metadata_));
  AppVisibleChanged_descriptor_ = file->message_type(4);
  static const int AppVisibleChanged_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AppVisibleChanged, visible_),
  };
  AppVisibleChanged_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      AppVisibleChanged_descriptor_,
      AppVisibleChanged::internal_default_instance(),
      AppVisibleChanged_offsets_,
      -1,
      -1,
      -1,
      sizeof(AppVisibleChanged),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AppVisibleChanged, _internal_metadata_));
  StoreEventsReq_descriptor_ = file->message_type(5);
  static const int StoreEventsReq_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StoreEventsReq, events_),
  };
  StoreEventsReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      StoreEventsReq_descriptor_,
      StoreEventsReq::internal_default_instance(),
      StoreEventsReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(StoreEventsReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StoreEventsReq, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_stats_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      EventRecord_descriptor_, EventRecord::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Event_descriptor_, Event::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      UntypedEvent_descriptor_, UntypedEvent::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ContentViewChanged_descriptor_, ContentViewChanged::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      AppVisibleChanged_descriptor_, AppVisibleChanged::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      StoreEventsReq_descriptor_, StoreEventsReq::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_stats_2eproto() {
  EventRecord_default_instance_.Shutdown();
  delete EventRecord_reflection_;
  Event_default_instance_.Shutdown();
  delete Event_reflection_;
  UntypedEvent_default_instance_.Shutdown();
  delete UntypedEvent_reflection_;
  ContentViewChanged_default_instance_.Shutdown();
  delete ContentViewChanged_reflection_;
  AppVisibleChanged_default_instance_.Shutdown();
  delete AppVisibleChanged_reflection_;
  StoreEventsReq_default_instance_.Shutdown();
  delete StoreEventsReq_reflection_;
}

void protobuf_InitDefaults_stats_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::zproto::protobuf_InitDefaults_types_2eproto();
  EventRecord_default_instance_.DefaultConstruct();
  Event_default_instance_.DefaultConstruct();
  ::google::protobuf::internal::GetEmptyString();
  UntypedEvent_default_instance_.DefaultConstruct();
  ::google::protobuf::internal::GetEmptyString();
  ContentViewChanged_default_instance_.DefaultConstruct();
  AppVisibleChanged_default_instance_.DefaultConstruct();
  StoreEventsReq_default_instance_.DefaultConstruct();
  EventRecord_default_instance_.get_mutable()->InitAsDefaultInstance();
  Event_default_instance_.get_mutable()->InitAsDefaultInstance();
  UntypedEvent_default_instance_.get_mutable()->InitAsDefaultInstance();
  ContentViewChanged_default_instance_.get_mutable()->InitAsDefaultInstance();
  AppVisibleChanged_default_instance_.get_mutable()->InitAsDefaultInstance();
  StoreEventsReq_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_stats_2eproto_once_);
void protobuf_InitDefaults_stats_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_stats_2eproto_once_,
                 &protobuf_InitDefaults_stats_2eproto_impl);
}
void protobuf_AddDesc_stats_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_stats_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013stats.proto\022\006zproto\032\013types.proto\"9\n\013Ev"
    "entRecord\022\014\n\004date\030\001 \001(\003\022\034\n\005event\030\002 \001(\0132\r"
    ".zproto.Event\"\007\n\005Event\"I\n\014UntypedEvent\022\022"
    "\n\nevent_type\030\001 \001(\t\022%\n\006params\030\002 \001(\0132\025.zpr"
    "oto.RawArrayValue\"v\n\022ContentViewChanged\022"
    "\024\n\014content_type\030\001 \001(\t\022\022\n\ncontent_id\030\002 \001("
    "\t\022\017\n\007visible\030\003 \001(\010\022%\n\006params\030\004 \001(\0132\025.zpr"
    "oto.RawArrayValue\"$\n\021AppVisibleChanged\022\017"
    "\n\007visible\030\001 \001(\010\"/\n\016StoreEventsReq\022\035\n\006eve"
    "nts\030\001 \003(\0132\r.zproto.EventB(\n\027com.zchat.en"
    "gine.zprotoB\013ZProtoStatsH\002b\006proto3", 434);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "stats.proto", &protobuf_RegisterTypes);
  ::zproto::protobuf_AddDesc_types_2eproto();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_stats_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_stats_2eproto_once_);
void protobuf_AddDesc_stats_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_stats_2eproto_once_,
                 &protobuf_AddDesc_stats_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_stats_2eproto {
  StaticDescriptorInitializer_stats_2eproto() {
    protobuf_AddDesc_stats_2eproto();
  }
} static_descriptor_initializer_stats_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int EventRecord::kDateFieldNumber;
const int EventRecord::kEventFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

EventRecord::EventRecord()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_stats_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.EventRecord)
}

void EventRecord::InitAsDefaultInstance() {
  event_ = const_cast< ::zproto::Event*>(
      ::zproto::Event::internal_default_instance());
}

EventRecord::EventRecord(const EventRecord& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.EventRecord)
}

void EventRecord::SharedCtor() {
  event_ = NULL;
  date_ = GOOGLE_LONGLONG(0);
  _cached_size_ = 0;
}

EventRecord::~EventRecord() {
  // @@protoc_insertion_point(destructor:zproto.EventRecord)
  SharedDtor();
}

void EventRecord::SharedDtor() {
  if (this != &EventRecord_default_instance_.get()) {
    delete event_;
  }
}

void EventRecord::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* EventRecord::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return EventRecord_descriptor_;
}

const EventRecord& EventRecord::default_instance() {
  protobuf_InitDefaults_stats_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<EventRecord> EventRecord_default_instance_;

EventRecord* EventRecord::New(::google::protobuf::Arena* arena) const {
  EventRecord* n = new EventRecord;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void EventRecord::UnsafeMergeFrom(const EventRecord& from) {
  MergeFrom(from);
}
void EventRecord::Swap(EventRecord* other) {
  if (other == this) return;
  InternalSwap(other);
}
void EventRecord::InternalSwap(EventRecord* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata EventRecord::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = EventRecord_descriptor_;
  metadata.reflection = EventRecord_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// EventRecord

// optional int64 date = 1;
void EventRecord::clear_date() {
  date_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 EventRecord::date() const {
  // @@protoc_insertion_point(field_get:zproto.EventRecord.date)
  return date_;
}
void EventRecord::set_date(::google::protobuf::int64 value) {
  
  date_ = value;
  // @@protoc_insertion_point(field_set:zproto.EventRecord.date)
}

// optional .zproto.Event event = 2;
bool EventRecord::has_event() const {
  return this != internal_default_instance() && event_ != NULL;
}
void EventRecord::clear_event() {
  if (GetArenaNoVirtual() == NULL && event_ != NULL) delete event_;
  event_ = NULL;
}
const ::zproto::Event& EventRecord::event() const {
  // @@protoc_insertion_point(field_get:zproto.EventRecord.event)
  return event_ != NULL ? *event_
                         : *::zproto::Event::internal_default_instance();
}
::zproto::Event* EventRecord::mutable_event() {
  
  if (event_ == NULL) {
    event_ = new ::zproto::Event;
  }
  // @@protoc_insertion_point(field_mutable:zproto.EventRecord.event)
  return event_;
}
::zproto::Event* EventRecord::release_event() {
  // @@protoc_insertion_point(field_release:zproto.EventRecord.event)
  
  ::zproto::Event* temp = event_;
  event_ = NULL;
  return temp;
}
void EventRecord::set_allocated_event(::zproto::Event* event) {
  delete event_;
  event_ = event;
  if (event) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:zproto.EventRecord.event)
}

inline const EventRecord* EventRecord::internal_default_instance() {
  return &EventRecord_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Event::Event()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_stats_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.Event)
}

void Event::InitAsDefaultInstance() {
}

Event::Event(const Event& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.Event)
}

void Event::SharedCtor() {
  _cached_size_ = 0;
}

Event::~Event() {
  // @@protoc_insertion_point(destructor:zproto.Event)
  SharedDtor();
}

void Event::SharedDtor() {
}

void Event::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Event::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Event_descriptor_;
}

const Event& Event::default_instance() {
  protobuf_InitDefaults_stats_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<Event> Event_default_instance_;

Event* Event::New(::google::protobuf::Arena* arena) const {
  Event* n = new Event;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Event::UnsafeMergeFrom(const Event& from) {
  MergeFrom(from);
}
void Event::Swap(Event* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Event::InternalSwap(Event* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata Event::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Event_descriptor_;
  metadata.reflection = Event_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Event

inline const Event* Event::internal_default_instance() {
  return &Event_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UntypedEvent::kEventTypeFieldNumber;
const int UntypedEvent::kParamsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UntypedEvent::UntypedEvent()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_stats_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.UntypedEvent)
}

void UntypedEvent::InitAsDefaultInstance() {
  params_ = const_cast< ::zproto::RawArrayValue*>(
      ::zproto::RawArrayValue::internal_default_instance());
}

UntypedEvent::UntypedEvent(const UntypedEvent& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.UntypedEvent)
}

void UntypedEvent::SharedCtor() {
  event_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  params_ = NULL;
  _cached_size_ = 0;
}

UntypedEvent::~UntypedEvent() {
  // @@protoc_insertion_point(destructor:zproto.UntypedEvent)
  SharedDtor();
}

void UntypedEvent::SharedDtor() {
  event_type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != &UntypedEvent_default_instance_.get()) {
    delete params_;
  }
}

void UntypedEvent::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UntypedEvent::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UntypedEvent_descriptor_;
}

const UntypedEvent& UntypedEvent::default_instance() {
  protobuf_InitDefaults_stats_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<UntypedEvent> UntypedEvent_default_instance_;

UntypedEvent* UntypedEvent::New(::google::protobuf::Arena* arena) const {
  UntypedEvent* n = new UntypedEvent;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void UntypedEvent::UnsafeMergeFrom(const UntypedEvent& from) {
  MergeFrom(from);
}
void UntypedEvent::Swap(UntypedEvent* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UntypedEvent::InternalSwap(UntypedEvent* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata UntypedEvent::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = UntypedEvent_descriptor_;
  metadata.reflection = UntypedEvent_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// UntypedEvent

// optional string event_type = 1;
void UntypedEvent::clear_event_type() {
  event_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& UntypedEvent::event_type() const {
  // @@protoc_insertion_point(field_get:zproto.UntypedEvent.event_type)
  return event_type_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void UntypedEvent::set_event_type(const ::std::string& value) {
  
  event_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.UntypedEvent.event_type)
}
void UntypedEvent::set_event_type(const char* value) {
  
  event_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.UntypedEvent.event_type)
}
void UntypedEvent::set_event_type(const char* value, size_t size) {
  
  event_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.UntypedEvent.event_type)
}
::std::string* UntypedEvent::mutable_event_type() {
  
  // @@protoc_insertion_point(field_mutable:zproto.UntypedEvent.event_type)
  return event_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* UntypedEvent::release_event_type() {
  // @@protoc_insertion_point(field_release:zproto.UntypedEvent.event_type)
  
  return event_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void UntypedEvent::set_allocated_event_type(::std::string* event_type) {
  if (event_type != NULL) {
    
  } else {
    
  }
  event_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), event_type);
  // @@protoc_insertion_point(field_set_allocated:zproto.UntypedEvent.event_type)
}

// optional .zproto.RawArrayValue params = 2;
bool UntypedEvent::has_params() const {
  return this != internal_default_instance() && params_ != NULL;
}
void UntypedEvent::clear_params() {
  if (GetArenaNoVirtual() == NULL && params_ != NULL) delete params_;
  params_ = NULL;
}
const ::zproto::RawArrayValue& UntypedEvent::params() const {
  // @@protoc_insertion_point(field_get:zproto.UntypedEvent.params)
  return params_ != NULL ? *params_
                         : *::zproto::RawArrayValue::internal_default_instance();
}
::zproto::RawArrayValue* UntypedEvent::mutable_params() {
  
  if (params_ == NULL) {
    params_ = new ::zproto::RawArrayValue;
  }
  // @@protoc_insertion_point(field_mutable:zproto.UntypedEvent.params)
  return params_;
}
::zproto::RawArrayValue* UntypedEvent::release_params() {
  // @@protoc_insertion_point(field_release:zproto.UntypedEvent.params)
  
  ::zproto::RawArrayValue* temp = params_;
  params_ = NULL;
  return temp;
}
void UntypedEvent::set_allocated_params(::zproto::RawArrayValue* params) {
  delete params_;
  params_ = params;
  if (params) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:zproto.UntypedEvent.params)
}

inline const UntypedEvent* UntypedEvent::internal_default_instance() {
  return &UntypedEvent_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ContentViewChanged::kContentTypeFieldNumber;
const int ContentViewChanged::kContentIdFieldNumber;
const int ContentViewChanged::kVisibleFieldNumber;
const int ContentViewChanged::kParamsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ContentViewChanged::ContentViewChanged()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_stats_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.ContentViewChanged)
}

void ContentViewChanged::InitAsDefaultInstance() {
  params_ = const_cast< ::zproto::RawArrayValue*>(
      ::zproto::RawArrayValue::internal_default_instance());
}

ContentViewChanged::ContentViewChanged(const ContentViewChanged& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.ContentViewChanged)
}

void ContentViewChanged::SharedCtor() {
  content_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  content_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  params_ = NULL;
  visible_ = false;
  _cached_size_ = 0;
}

ContentViewChanged::~ContentViewChanged() {
  // @@protoc_insertion_point(destructor:zproto.ContentViewChanged)
  SharedDtor();
}

void ContentViewChanged::SharedDtor() {
  content_type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  content_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != &ContentViewChanged_default_instance_.get()) {
    delete params_;
  }
}

void ContentViewChanged::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ContentViewChanged::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ContentViewChanged_descriptor_;
}

const ContentViewChanged& ContentViewChanged::default_instance() {
  protobuf_InitDefaults_stats_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<ContentViewChanged> ContentViewChanged_default_instance_;

ContentViewChanged* ContentViewChanged::New(::google::protobuf::Arena* arena) const {
  ContentViewChanged* n = new ContentViewChanged;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ContentViewChanged::UnsafeMergeFrom(const ContentViewChanged& from) {
  MergeFrom(from);
}
void ContentViewChanged::Swap(ContentViewChanged* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ContentViewChanged::InternalSwap(ContentViewChanged* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata ContentViewChanged::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ContentViewChanged_descriptor_;
  metadata.reflection = ContentViewChanged_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ContentViewChanged

// optional string content_type = 1;
void ContentViewChanged::clear_content_type() {
  content_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& ContentViewChanged::content_type() const {
  // @@protoc_insertion_point(field_get:zproto.ContentViewChanged.content_type)
  return content_type_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ContentViewChanged::set_content_type(const ::std::string& value) {
  
  content_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.ContentViewChanged.content_type)
}
void ContentViewChanged::set_content_type(const char* value) {
  
  content_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.ContentViewChanged.content_type)
}
void ContentViewChanged::set_content_type(const char* value, size_t size) {
  
  content_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.ContentViewChanged.content_type)
}
::std::string* ContentViewChanged::mutable_content_type() {
  
  // @@protoc_insertion_point(field_mutable:zproto.ContentViewChanged.content_type)
  return content_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* ContentViewChanged::release_content_type() {
  // @@protoc_insertion_point(field_release:zproto.ContentViewChanged.content_type)
  
  return content_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ContentViewChanged::set_allocated_content_type(::std::string* content_type) {
  if (content_type != NULL) {
    
  } else {
    
  }
  content_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), content_type);
  // @@protoc_insertion_point(field_set_allocated:zproto.ContentViewChanged.content_type)
}

// optional string content_id = 2;
void ContentViewChanged::clear_content_id() {
  content_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& ContentViewChanged::content_id() const {
  // @@protoc_insertion_point(field_get:zproto.ContentViewChanged.content_id)
  return content_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ContentViewChanged::set_content_id(const ::std::string& value) {
  
  content_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.ContentViewChanged.content_id)
}
void ContentViewChanged::set_content_id(const char* value) {
  
  content_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.ContentViewChanged.content_id)
}
void ContentViewChanged::set_content_id(const char* value, size_t size) {
  
  content_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.ContentViewChanged.content_id)
}
::std::string* ContentViewChanged::mutable_content_id() {
  
  // @@protoc_insertion_point(field_mutable:zproto.ContentViewChanged.content_id)
  return content_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* ContentViewChanged::release_content_id() {
  // @@protoc_insertion_point(field_release:zproto.ContentViewChanged.content_id)
  
  return content_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ContentViewChanged::set_allocated_content_id(::std::string* content_id) {
  if (content_id != NULL) {
    
  } else {
    
  }
  content_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), content_id);
  // @@protoc_insertion_point(field_set_allocated:zproto.ContentViewChanged.content_id)
}

// optional bool visible = 3;
void ContentViewChanged::clear_visible() {
  visible_ = false;
}
bool ContentViewChanged::visible() const {
  // @@protoc_insertion_point(field_get:zproto.ContentViewChanged.visible)
  return visible_;
}
void ContentViewChanged::set_visible(bool value) {
  
  visible_ = value;
  // @@protoc_insertion_point(field_set:zproto.ContentViewChanged.visible)
}

// optional .zproto.RawArrayValue params = 4;
bool ContentViewChanged::has_params() const {
  return this != internal_default_instance() && params_ != NULL;
}
void ContentViewChanged::clear_params() {
  if (GetArenaNoVirtual() == NULL && params_ != NULL) delete params_;
  params_ = NULL;
}
const ::zproto::RawArrayValue& ContentViewChanged::params() const {
  // @@protoc_insertion_point(field_get:zproto.ContentViewChanged.params)
  return params_ != NULL ? *params_
                         : *::zproto::RawArrayValue::internal_default_instance();
}
::zproto::RawArrayValue* ContentViewChanged::mutable_params() {
  
  if (params_ == NULL) {
    params_ = new ::zproto::RawArrayValue;
  }
  // @@protoc_insertion_point(field_mutable:zproto.ContentViewChanged.params)
  return params_;
}
::zproto::RawArrayValue* ContentViewChanged::release_params() {
  // @@protoc_insertion_point(field_release:zproto.ContentViewChanged.params)
  
  ::zproto::RawArrayValue* temp = params_;
  params_ = NULL;
  return temp;
}
void ContentViewChanged::set_allocated_params(::zproto::RawArrayValue* params) {
  delete params_;
  params_ = params;
  if (params) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:zproto.ContentViewChanged.params)
}

inline const ContentViewChanged* ContentViewChanged::internal_default_instance() {
  return &ContentViewChanged_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AppVisibleChanged::kVisibleFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AppVisibleChanged::AppVisibleChanged()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_stats_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.AppVisibleChanged)
}

void AppVisibleChanged::InitAsDefaultInstance() {
}

AppVisibleChanged::AppVisibleChanged(const AppVisibleChanged& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.AppVisibleChanged)
}

void AppVisibleChanged::SharedCtor() {
  visible_ = false;
  _cached_size_ = 0;
}

AppVisibleChanged::~AppVisibleChanged() {
  // @@protoc_insertion_point(destructor:zproto.AppVisibleChanged)
  SharedDtor();
}

void AppVisibleChanged::SharedDtor() {
}

void AppVisibleChanged::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AppVisibleChanged::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AppVisibleChanged_descriptor_;
}

const AppVisibleChanged& AppVisibleChanged::default_instance() {
  protobuf_InitDefaults_stats_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<AppVisibleChanged> AppVisibleChanged_default_instance_;

AppVisibleChanged* AppVisibleChanged::New(::google::protobuf::Arena* arena) const {
  AppVisibleChanged* n = new AppVisibleChanged;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void AppVisibleChanged::UnsafeMergeFrom(const AppVisibleChanged& from) {
  MergeFrom(from);
}
void AppVisibleChanged::Swap(AppVisibleChanged* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AppVisibleChanged::InternalSwap(AppVisibleChanged* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata AppVisibleChanged::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AppVisibleChanged_descriptor_;
  metadata.reflection = AppVisibleChanged_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// AppVisibleChanged

// optional bool visible = 1;
void AppVisibleChanged::clear_visible() {
  visible_ = false;
}
bool AppVisibleChanged::visible() const {
  // @@protoc_insertion_point(field_get:zproto.AppVisibleChanged.visible)
  return visible_;
}
void AppVisibleChanged::set_visible(bool value) {
  
  visible_ = value;
  // @@protoc_insertion_point(field_set:zproto.AppVisibleChanged.visible)
}

inline const AppVisibleChanged* AppVisibleChanged::internal_default_instance() {
  return &AppVisibleChanged_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StoreEventsReq::kEventsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StoreEventsReq::StoreEventsReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_stats_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.StoreEventsReq)
}

void StoreEventsReq::InitAsDefaultInstance() {
}

StoreEventsReq::StoreEventsReq(const StoreEventsReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.StoreEventsReq)
}

void StoreEventsReq::SharedCtor() {
  _cached_size_ = 0;
}

StoreEventsReq::~StoreEventsReq() {
  // @@protoc_insertion_point(destructor:zproto.StoreEventsReq)
  SharedDtor();
}

void StoreEventsReq::SharedDtor() {
}

void StoreEventsReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StoreEventsReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return StoreEventsReq_descriptor_;
}

const StoreEventsReq& StoreEventsReq::default_instance() {
  protobuf_InitDefaults_stats_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<StoreEventsReq> StoreEventsReq_default_instance_;

StoreEventsReq* StoreEventsReq::New(::google::protobuf::Arena* arena) const {
  StoreEventsReq* n = new StoreEventsReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void StoreEventsReq::UnsafeMergeFrom(const StoreEventsReq& from) {
  MergeFrom(from);
}
void StoreEventsReq::Swap(StoreEventsReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StoreEventsReq::InternalSwap(StoreEventsReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata StoreEventsReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = StoreEventsReq_descriptor_;
  metadata.reflection = StoreEventsReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// StoreEventsReq

// repeated .zproto.Event events = 1;
int StoreEventsReq::events_size() const {
  return events_.size();
}
void StoreEventsReq::clear_events() {
  events_.Clear();
}
const ::zproto::Event& StoreEventsReq::events(int index) const {
  // @@protoc_insertion_point(field_get:zproto.StoreEventsReq.events)
  return events_.Get(index);
}
::zproto::Event* StoreEventsReq::mutable_events(int index) {
  // @@protoc_insertion_point(field_mutable:zproto.StoreEventsReq.events)
  return events_.Mutable(index);
}
::zproto::Event* StoreEventsReq::add_events() {
  // @@protoc_insertion_point(field_add:zproto.StoreEventsReq.events)
  return events_.Add();
}
::google::protobuf::RepeatedPtrField< ::zproto::Event >*
StoreEventsReq::mutable_events() {
  // @@protoc_insertion_point(field_mutable_list:zproto.StoreEventsReq.events)
  return &events_;
}
const ::google::protobuf::RepeatedPtrField< ::zproto::Event >&
StoreEventsReq::events() const {
  // @@protoc_insertion_point(field_list:zproto.StoreEventsReq.events)
  return events_;
}

inline const StoreEventsReq* StoreEventsReq::internal_default_instance() {
  return &StoreEventsReq_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace zproto

// @@protoc_insertion_point(global_scope)
