// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "types.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace zproto {

namespace {

const ::google::protobuf::Descriptor* RawValue_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RawValue_reflection_ = NULL;
const ::google::protobuf::Descriptor* RawArrayValue_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RawArrayValue_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* DataType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_types_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_types_2eproto() {
  protobuf_AddDesc_types_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "types.proto");
  GOOGLE_CHECK(file != NULL);
  RawValue_descriptor_ = file->message_type(0);
  static const int RawValue_offsets_[13] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RawValue, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RawValue, int32_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RawValue, int64_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RawValue, uint32_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RawValue, uint64_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RawValue, float_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RawValue, double_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RawValue, bool_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RawValue, date_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RawValue, datetime_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RawValue, binary_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RawValue, string_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RawValue, data_type_value_),
  };
  RawValue_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      RawValue_descriptor_,
      RawValue::internal_default_instance(),
      RawValue_offsets_,
      -1,
      -1,
      -1,
      sizeof(RawValue),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RawValue, _internal_metadata_));
  RawArrayValue_descriptor_ = file->message_type(1);
  static const int RawArrayValue_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RawArrayValue, array_),
  };
  RawArrayValue_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      RawArrayValue_descriptor_,
      RawArrayValue::internal_default_instance(),
      RawArrayValue_offsets_,
      -1,
      -1,
      -1,
      sizeof(RawArrayValue),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RawArrayValue, _internal_metadata_));
  DataType_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_types_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      RawValue_descriptor_, RawValue::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      RawArrayValue_descriptor_, RawArrayValue::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_types_2eproto() {
  RawValue_default_instance_.Shutdown();
  delete RawValue_reflection_;
  RawArrayValue_default_instance_.Shutdown();
  delete RawArrayValue_reflection_;
}

void protobuf_InitDefaults_types_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::GetEmptyString();
  RawValue_default_instance_.DefaultConstruct();
  RawArrayValue_default_instance_.DefaultConstruct();
  RawValue_default_instance_.get_mutable()->InitAsDefaultInstance();
  RawArrayValue_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_types_2eproto_once_);
void protobuf_InitDefaults_types_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_types_2eproto_once_,
                 &protobuf_InitDefaults_types_2eproto_impl);
}
void protobuf_AddDesc_types_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_types_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013types.proto\022\006zproto\"\302\002\n\010RawValue\022\036\n\004ty"
    "pe\030\001 \001(\0162\020.zproto.DataType\022\023\n\013int32_valu"
    "e\030\002 \001(\005\022\023\n\013int64_value\030\003 \001(\003\022\024\n\014uint32_v"
    "alue\030\004 \001(\r\022\024\n\014uint64_value\030\005 \001(\004\022\023\n\013floa"
    "t_value\030\006 \001(\002\022\024\n\014double_value\030\007 \001(\001\022\022\n\nb"
    "ool_value\030\010 \001(\010\022\022\n\ndate_value\030\t \001(\005\022\026\n\016d"
    "atetime_value\030\n \001(\003\022\024\n\014binary_value\030\013 \001("
    "\014\022\024\n\014string_value\030\014 \001(\t\022)\n\017data_type_val"
    "ue\030\r \001(\0162\020.zproto.DataType\"0\n\rRawArrayVa"
    "lue\022\037\n\005array\030\001 \003(\0132\020.zproto.RawValue*\242\001\n"
    "\010DataType\022\t\n\005INT32\020\000\022\t\n\005INT64\020\001\022\n\n\006UINT3"
    "2\020\002\022\n\n\006UINT64\020\003\022\t\n\005FLOAT\020\004\022\n\n\006DOUBLE\020\005\022\010"
    "\n\004BOOL\020\006\022\010\n\004DATE\020\007\022\014\n\010DATETIME\020\010\022\n\n\006STRI"
    "NG\020\t\022\n\n\006BINARY\020\n\022\010\n\004ENUM\020\013\022\r\n\tDATA_TYPE\020"
    "\014B.\n\027com.zchat.engine.zprotoB\021ZProtoColl"
    "ectionsH\002b\006proto3", 617);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "types.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_types_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_types_2eproto_once_);
void protobuf_AddDesc_types_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_types_2eproto_once_,
                 &protobuf_AddDesc_types_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_types_2eproto {
  StaticDescriptorInitializer_types_2eproto() {
    protobuf_AddDesc_types_2eproto();
  }
} static_descriptor_initializer_types_2eproto_;
const ::google::protobuf::EnumDescriptor* DataType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DataType_descriptor_;
}
bool DataType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RawValue::kTypeFieldNumber;
const int RawValue::kInt32ValueFieldNumber;
const int RawValue::kInt64ValueFieldNumber;
const int RawValue::kUint32ValueFieldNumber;
const int RawValue::kUint64ValueFieldNumber;
const int RawValue::kFloatValueFieldNumber;
const int RawValue::kDoubleValueFieldNumber;
const int RawValue::kBoolValueFieldNumber;
const int RawValue::kDateValueFieldNumber;
const int RawValue::kDatetimeValueFieldNumber;
const int RawValue::kBinaryValueFieldNumber;
const int RawValue::kStringValueFieldNumber;
const int RawValue::kDataTypeValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RawValue::RawValue()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_types_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.RawValue)
}

void RawValue::InitAsDefaultInstance() {
}

RawValue::RawValue(const RawValue& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.RawValue)
}

void RawValue::SharedCtor() {
  binary_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&type_, 0, reinterpret_cast<char*>(&data_type_value_) -
    reinterpret_cast<char*>(&type_) + sizeof(data_type_value_));
  _cached_size_ = 0;
}

RawValue::~RawValue() {
  // @@protoc_insertion_point(destructor:zproto.RawValue)
  SharedDtor();
}

void RawValue::SharedDtor() {
  binary_value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  string_value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void RawValue::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RawValue::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RawValue_descriptor_;
}

const RawValue& RawValue::default_instance() {
  protobuf_InitDefaults_types_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<RawValue> RawValue_default_instance_;

RawValue* RawValue::New(::google::protobuf::Arena* arena) const {
  RawValue* n = new RawValue;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RawValue::UnsafeMergeFrom(const RawValue& from) {
  MergeFrom(from);
}
void RawValue::Swap(RawValue* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RawValue::InternalSwap(RawValue* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata RawValue::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RawValue_descriptor_;
  metadata.reflection = RawValue_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RawValue

// optional .zproto.DataType type = 1;
void RawValue::clear_type() {
  type_ = 0;
}
::zproto::DataType RawValue::type() const {
  // @@protoc_insertion_point(field_get:zproto.RawValue.type)
  return static_cast< ::zproto::DataType >(type_);
}
void RawValue::set_type(::zproto::DataType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:zproto.RawValue.type)
}

// optional int32 int32_value = 2;
void RawValue::clear_int32_value() {
  int32_value_ = 0;
}
::google::protobuf::int32 RawValue::int32_value() const {
  // @@protoc_insertion_point(field_get:zproto.RawValue.int32_value)
  return int32_value_;
}
void RawValue::set_int32_value(::google::protobuf::int32 value) {
  
  int32_value_ = value;
  // @@protoc_insertion_point(field_set:zproto.RawValue.int32_value)
}

// optional int64 int64_value = 3;
void RawValue::clear_int64_value() {
  int64_value_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 RawValue::int64_value() const {
  // @@protoc_insertion_point(field_get:zproto.RawValue.int64_value)
  return int64_value_;
}
void RawValue::set_int64_value(::google::protobuf::int64 value) {
  
  int64_value_ = value;
  // @@protoc_insertion_point(field_set:zproto.RawValue.int64_value)
}

// optional uint32 uint32_value = 4;
void RawValue::clear_uint32_value() {
  uint32_value_ = 0u;
}
::google::protobuf::uint32 RawValue::uint32_value() const {
  // @@protoc_insertion_point(field_get:zproto.RawValue.uint32_value)
  return uint32_value_;
}
void RawValue::set_uint32_value(::google::protobuf::uint32 value) {
  
  uint32_value_ = value;
  // @@protoc_insertion_point(field_set:zproto.RawValue.uint32_value)
}

// optional uint64 uint64_value = 5;
void RawValue::clear_uint64_value() {
  uint64_value_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 RawValue::uint64_value() const {
  // @@protoc_insertion_point(field_get:zproto.RawValue.uint64_value)
  return uint64_value_;
}
void RawValue::set_uint64_value(::google::protobuf::uint64 value) {
  
  uint64_value_ = value;
  // @@protoc_insertion_point(field_set:zproto.RawValue.uint64_value)
}

// optional float float_value = 6;
void RawValue::clear_float_value() {
  float_value_ = 0;
}
float RawValue::float_value() const {
  // @@protoc_insertion_point(field_get:zproto.RawValue.float_value)
  return float_value_;
}
void RawValue::set_float_value(float value) {
  
  float_value_ = value;
  // @@protoc_insertion_point(field_set:zproto.RawValue.float_value)
}

// optional double double_value = 7;
void RawValue::clear_double_value() {
  double_value_ = 0;
}
double RawValue::double_value() const {
  // @@protoc_insertion_point(field_get:zproto.RawValue.double_value)
  return double_value_;
}
void RawValue::set_double_value(double value) {
  
  double_value_ = value;
  // @@protoc_insertion_point(field_set:zproto.RawValue.double_value)
}

// optional bool bool_value = 8;
void RawValue::clear_bool_value() {
  bool_value_ = false;
}
bool RawValue::bool_value() const {
  // @@protoc_insertion_point(field_get:zproto.RawValue.bool_value)
  return bool_value_;
}
void RawValue::set_bool_value(bool value) {
  
  bool_value_ = value;
  // @@protoc_insertion_point(field_set:zproto.RawValue.bool_value)
}

// optional int32 date_value = 9;
void RawValue::clear_date_value() {
  date_value_ = 0;
}
::google::protobuf::int32 RawValue::date_value() const {
  // @@protoc_insertion_point(field_get:zproto.RawValue.date_value)
  return date_value_;
}
void RawValue::set_date_value(::google::protobuf::int32 value) {
  
  date_value_ = value;
  // @@protoc_insertion_point(field_set:zproto.RawValue.date_value)
}

// optional int64 datetime_value = 10;
void RawValue::clear_datetime_value() {
  datetime_value_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 RawValue::datetime_value() const {
  // @@protoc_insertion_point(field_get:zproto.RawValue.datetime_value)
  return datetime_value_;
}
void RawValue::set_datetime_value(::google::protobuf::int64 value) {
  
  datetime_value_ = value;
  // @@protoc_insertion_point(field_set:zproto.RawValue.datetime_value)
}

// optional bytes binary_value = 11;
void RawValue::clear_binary_value() {
  binary_value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& RawValue::binary_value() const {
  // @@protoc_insertion_point(field_get:zproto.RawValue.binary_value)
  return binary_value_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void RawValue::set_binary_value(const ::std::string& value) {
  
  binary_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.RawValue.binary_value)
}
void RawValue::set_binary_value(const char* value) {
  
  binary_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.RawValue.binary_value)
}
void RawValue::set_binary_value(const void* value, size_t size) {
  
  binary_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.RawValue.binary_value)
}
::std::string* RawValue::mutable_binary_value() {
  
  // @@protoc_insertion_point(field_mutable:zproto.RawValue.binary_value)
  return binary_value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* RawValue::release_binary_value() {
  // @@protoc_insertion_point(field_release:zproto.RawValue.binary_value)
  
  return binary_value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void RawValue::set_allocated_binary_value(::std::string* binary_value) {
  if (binary_value != NULL) {
    
  } else {
    
  }
  binary_value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), binary_value);
  // @@protoc_insertion_point(field_set_allocated:zproto.RawValue.binary_value)
}

// optional string string_value = 12;
void RawValue::clear_string_value() {
  string_value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& RawValue::string_value() const {
  // @@protoc_insertion_point(field_get:zproto.RawValue.string_value)
  return string_value_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void RawValue::set_string_value(const ::std::string& value) {
  
  string_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.RawValue.string_value)
}
void RawValue::set_string_value(const char* value) {
  
  string_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.RawValue.string_value)
}
void RawValue::set_string_value(const char* value, size_t size) {
  
  string_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.RawValue.string_value)
}
::std::string* RawValue::mutable_string_value() {
  
  // @@protoc_insertion_point(field_mutable:zproto.RawValue.string_value)
  return string_value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* RawValue::release_string_value() {
  // @@protoc_insertion_point(field_release:zproto.RawValue.string_value)
  
  return string_value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void RawValue::set_allocated_string_value(::std::string* string_value) {
  if (string_value != NULL) {
    
  } else {
    
  }
  string_value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), string_value);
  // @@protoc_insertion_point(field_set_allocated:zproto.RawValue.string_value)
}

// optional .zproto.DataType data_type_value = 13;
void RawValue::clear_data_type_value() {
  data_type_value_ = 0;
}
::zproto::DataType RawValue::data_type_value() const {
  // @@protoc_insertion_point(field_get:zproto.RawValue.data_type_value)
  return static_cast< ::zproto::DataType >(data_type_value_);
}
void RawValue::set_data_type_value(::zproto::DataType value) {
  
  data_type_value_ = value;
  // @@protoc_insertion_point(field_set:zproto.RawValue.data_type_value)
}

inline const RawValue* RawValue::internal_default_instance() {
  return &RawValue_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RawArrayValue::kArrayFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RawArrayValue::RawArrayValue()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_types_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.RawArrayValue)
}

void RawArrayValue::InitAsDefaultInstance() {
}

RawArrayValue::RawArrayValue(const RawArrayValue& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.RawArrayValue)
}

void RawArrayValue::SharedCtor() {
  _cached_size_ = 0;
}

RawArrayValue::~RawArrayValue() {
  // @@protoc_insertion_point(destructor:zproto.RawArrayValue)
  SharedDtor();
}

void RawArrayValue::SharedDtor() {
}

void RawArrayValue::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RawArrayValue::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RawArrayValue_descriptor_;
}

const RawArrayValue& RawArrayValue::default_instance() {
  protobuf_InitDefaults_types_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<RawArrayValue> RawArrayValue_default_instance_;

RawArrayValue* RawArrayValue::New(::google::protobuf::Arena* arena) const {
  RawArrayValue* n = new RawArrayValue;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RawArrayValue::UnsafeMergeFrom(const RawArrayValue& from) {
  MergeFrom(from);
}
void RawArrayValue::Swap(RawArrayValue* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RawArrayValue::InternalSwap(RawArrayValue* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata RawArrayValue::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RawArrayValue_descriptor_;
  metadata.reflection = RawArrayValue_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RawArrayValue

// repeated .zproto.RawValue array = 1;
int RawArrayValue::array_size() const {
  return array_.size();
}
void RawArrayValue::clear_array() {
  array_.Clear();
}
const ::zproto::RawValue& RawArrayValue::array(int index) const {
  // @@protoc_insertion_point(field_get:zproto.RawArrayValue.array)
  return array_.Get(index);
}
::zproto::RawValue* RawArrayValue::mutable_array(int index) {
  // @@protoc_insertion_point(field_mutable:zproto.RawArrayValue.array)
  return array_.Mutable(index);
}
::zproto::RawValue* RawArrayValue::add_array() {
  // @@protoc_insertion_point(field_add:zproto.RawArrayValue.array)
  return array_.Add();
}
::google::protobuf::RepeatedPtrField< ::zproto::RawValue >*
RawArrayValue::mutable_array() {
  // @@protoc_insertion_point(field_mutable_list:zproto.RawArrayValue.array)
  return &array_;
}
const ::google::protobuf::RepeatedPtrField< ::zproto::RawValue >&
RawArrayValue::array() const {
  // @@protoc_insertion_point(field_list:zproto.RawArrayValue.array)
  return array_;
}

inline const RawArrayValue* RawArrayValue::internal_default_instance() {
  return &RawArrayValue_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace zproto

// @@protoc_insertion_point(global_scope)
