// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weak.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "weak.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace zproto {

namespace {

const ::google::protobuf::Descriptor* TypingReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TypingReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* StopTypingReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  StopTypingReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* SetOnlineReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SetOnlineReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* PauseNotificationsNotify_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PauseNotificationsNotify_reflection_ = NULL;
const ::google::protobuf::Descriptor* RestoreNotificationsNotify_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RestoreNotificationsNotify_reflection_ = NULL;
const ::google::protobuf::Descriptor* PauseNotificationsReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PauseNotificationsReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* RestoreNotificationsReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RestoreNotificationsReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* TypingNotify_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TypingNotify_reflection_ = NULL;
const ::google::protobuf::Descriptor* TypingStopNotify_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TypingStopNotify_reflection_ = NULL;
const ::google::protobuf::Descriptor* UserOnlineNotify_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  UserOnlineNotify_reflection_ = NULL;
const ::google::protobuf::Descriptor* UserOfflineNotify_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  UserOfflineNotify_reflection_ = NULL;
const ::google::protobuf::Descriptor* UserLastSeenNotify_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  UserLastSeenNotify_reflection_ = NULL;
const ::google::protobuf::Descriptor* GroupOnlineNotify_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GroupOnlineNotify_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* TypingType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* DeviceType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_weak_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_weak_2eproto() {
  protobuf_AddDesc_weak_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "weak.proto");
  GOOGLE_CHECK(file != NULL);
  TypingReq_descriptor_ = file->message_type(0);
  static const int TypingReq_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TypingReq, peer_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TypingReq, typing_type_),
  };
  TypingReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      TypingReq_descriptor_,
      TypingReq::internal_default_instance(),
      TypingReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(TypingReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TypingReq, _internal_metadata_));
  StopTypingReq_descriptor_ = file->message_type(1);
  static const int StopTypingReq_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StopTypingReq, peer_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StopTypingReq, typing_type_),
  };
  StopTypingReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      StopTypingReq_descriptor_,
      StopTypingReq::internal_default_instance(),
      StopTypingReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(StopTypingReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StopTypingReq, _internal_metadata_));
  SetOnlineReq_descriptor_ = file->message_type(2);
  static const int SetOnlineReq_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SetOnlineReq, is_online_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SetOnlineReq, timeout_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SetOnlineReq, device_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SetOnlineReq, device_category_),
  };
  SetOnlineReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SetOnlineReq_descriptor_,
      SetOnlineReq::internal_default_instance(),
      SetOnlineReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(SetOnlineReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SetOnlineReq, _internal_metadata_));
  PauseNotificationsNotify_descriptor_ = file->message_type(3);
  static const int PauseNotificationsNotify_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PauseNotificationsNotify, timeout_),
  };
  PauseNotificationsNotify_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PauseNotificationsNotify_descriptor_,
      PauseNotificationsNotify::internal_default_instance(),
      PauseNotificationsNotify_offsets_,
      -1,
      -1,
      -1,
      sizeof(PauseNotificationsNotify),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PauseNotificationsNotify, _internal_metadata_));
  RestoreNotificationsNotify_descriptor_ = file->message_type(4);
  static const int RestoreNotificationsNotify_offsets_[1] = {
  };
  RestoreNotificationsNotify_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      RestoreNotificationsNotify_descriptor_,
      RestoreNotificationsNotify::internal_default_instance(),
      RestoreNotificationsNotify_offsets_,
      -1,
      -1,
      -1,
      sizeof(RestoreNotificationsNotify),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RestoreNotificationsNotify, _internal_metadata_));
  PauseNotificationsReq_descriptor_ = file->message_type(5);
  static const int PauseNotificationsReq_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PauseNotificationsReq, timeout_),
  };
  PauseNotificationsReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PauseNotificationsReq_descriptor_,
      PauseNotificationsReq::internal_default_instance(),
      PauseNotificationsReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(PauseNotificationsReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PauseNotificationsReq, _internal_metadata_));
  RestoreNotificationsReq_descriptor_ = file->message_type(6);
  static const int RestoreNotificationsReq_offsets_[1] = {
  };
  RestoreNotificationsReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      RestoreNotificationsReq_descriptor_,
      RestoreNotificationsReq::internal_default_instance(),
      RestoreNotificationsReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(RestoreNotificationsReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RestoreNotificationsReq, _internal_metadata_));
  TypingNotify_descriptor_ = file->message_type(7);
  static const int TypingNotify_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TypingNotify, peer_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TypingNotify, uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TypingNotify, typing_type_),
  };
  TypingNotify_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      TypingNotify_descriptor_,
      TypingNotify::internal_default_instance(),
      TypingNotify_offsets_,
      -1,
      -1,
      -1,
      sizeof(TypingNotify),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TypingNotify, _internal_metadata_));
  TypingStopNotify_descriptor_ = file->message_type(8);
  static const int TypingStopNotify_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TypingStopNotify, peer_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TypingStopNotify, uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TypingStopNotify, typing_type_),
  };
  TypingStopNotify_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      TypingStopNotify_descriptor_,
      TypingStopNotify::internal_default_instance(),
      TypingStopNotify_offsets_,
      -1,
      -1,
      -1,
      sizeof(TypingStopNotify),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TypingStopNotify, _internal_metadata_));
  UserOnlineNotify_descriptor_ = file->message_type(9);
  static const int UserOnlineNotify_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserOnlineNotify, uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserOnlineNotify, device_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserOnlineNotify, device_category_),
  };
  UserOnlineNotify_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      UserOnlineNotify_descriptor_,
      UserOnlineNotify::internal_default_instance(),
      UserOnlineNotify_offsets_,
      -1,
      -1,
      -1,
      sizeof(UserOnlineNotify),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserOnlineNotify, _internal_metadata_));
  UserOfflineNotify_descriptor_ = file->message_type(10);
  static const int UserOfflineNotify_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserOfflineNotify, uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserOfflineNotify, device_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserOfflineNotify, device_category_),
  };
  UserOfflineNotify_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      UserOfflineNotify_descriptor_,
      UserOfflineNotify::internal_default_instance(),
      UserOfflineNotify_offsets_,
      -1,
      -1,
      -1,
      sizeof(UserOfflineNotify),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserOfflineNotify, _internal_metadata_));
  UserLastSeenNotify_descriptor_ = file->message_type(11);
  static const int UserLastSeenNotify_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserLastSeenNotify, uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserLastSeenNotify, date_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserLastSeenNotify, device_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserLastSeenNotify, device_category_),
  };
  UserLastSeenNotify_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      UserLastSeenNotify_descriptor_,
      UserLastSeenNotify::internal_default_instance(),
      UserLastSeenNotify_offsets_,
      -1,
      -1,
      -1,
      sizeof(UserLastSeenNotify),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserLastSeenNotify, _internal_metadata_));
  GroupOnlineNotify_descriptor_ = file->message_type(12);
  static const int GroupOnlineNotify_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroupOnlineNotify, group_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroupOnlineNotify, count_),
  };
  GroupOnlineNotify_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      GroupOnlineNotify_descriptor_,
      GroupOnlineNotify::internal_default_instance(),
      GroupOnlineNotify_offsets_,
      -1,
      -1,
      -1,
      sizeof(GroupOnlineNotify),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroupOnlineNotify, _internal_metadata_));
  TypingType_descriptor_ = file->enum_type(0);
  DeviceType_descriptor_ = file->enum_type(1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_weak_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      TypingReq_descriptor_, TypingReq::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      StopTypingReq_descriptor_, StopTypingReq::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SetOnlineReq_descriptor_, SetOnlineReq::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PauseNotificationsNotify_descriptor_, PauseNotificationsNotify::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      RestoreNotificationsNotify_descriptor_, RestoreNotificationsNotify::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PauseNotificationsReq_descriptor_, PauseNotificationsReq::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      RestoreNotificationsReq_descriptor_, RestoreNotificationsReq::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      TypingNotify_descriptor_, TypingNotify::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      TypingStopNotify_descriptor_, TypingStopNotify::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      UserOnlineNotify_descriptor_, UserOnlineNotify::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      UserOfflineNotify_descriptor_, UserOfflineNotify::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      UserLastSeenNotify_descriptor_, UserLastSeenNotify::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      GroupOnlineNotify_descriptor_, GroupOnlineNotify::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_weak_2eproto() {
  TypingReq_default_instance_.Shutdown();
  delete TypingReq_reflection_;
  StopTypingReq_default_instance_.Shutdown();
  delete StopTypingReq_reflection_;
  SetOnlineReq_default_instance_.Shutdown();
  delete SetOnlineReq_reflection_;
  PauseNotificationsNotify_default_instance_.Shutdown();
  delete PauseNotificationsNotify_reflection_;
  RestoreNotificationsNotify_default_instance_.Shutdown();
  delete RestoreNotificationsNotify_reflection_;
  PauseNotificationsReq_default_instance_.Shutdown();
  delete PauseNotificationsReq_reflection_;
  RestoreNotificationsReq_default_instance_.Shutdown();
  delete RestoreNotificationsReq_reflection_;
  TypingNotify_default_instance_.Shutdown();
  delete TypingNotify_reflection_;
  TypingStopNotify_default_instance_.Shutdown();
  delete TypingStopNotify_reflection_;
  UserOnlineNotify_default_instance_.Shutdown();
  delete UserOnlineNotify_reflection_;
  UserOfflineNotify_default_instance_.Shutdown();
  delete UserOfflineNotify_reflection_;
  UserLastSeenNotify_default_instance_.Shutdown();
  delete UserLastSeenNotify_reflection_;
  GroupOnlineNotify_default_instance_.Shutdown();
  delete GroupOnlineNotify_reflection_;
}

void protobuf_InitDefaults_weak_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::zproto::protobuf_InitDefaults_peers_2eproto();
  TypingReq_default_instance_.DefaultConstruct();
  StopTypingReq_default_instance_.DefaultConstruct();
  ::google::protobuf::internal::GetEmptyString();
  SetOnlineReq_default_instance_.DefaultConstruct();
  PauseNotificationsNotify_default_instance_.DefaultConstruct();
  RestoreNotificationsNotify_default_instance_.DefaultConstruct();
  PauseNotificationsReq_default_instance_.DefaultConstruct();
  RestoreNotificationsReq_default_instance_.DefaultConstruct();
  TypingNotify_default_instance_.DefaultConstruct();
  TypingStopNotify_default_instance_.DefaultConstruct();
  ::google::protobuf::internal::GetEmptyString();
  UserOnlineNotify_default_instance_.DefaultConstruct();
  ::google::protobuf::internal::GetEmptyString();
  UserOfflineNotify_default_instance_.DefaultConstruct();
  ::google::protobuf::internal::GetEmptyString();
  UserLastSeenNotify_default_instance_.DefaultConstruct();
  GroupOnlineNotify_default_instance_.DefaultConstruct();
  TypingReq_default_instance_.get_mutable()->InitAsDefaultInstance();
  StopTypingReq_default_instance_.get_mutable()->InitAsDefaultInstance();
  SetOnlineReq_default_instance_.get_mutable()->InitAsDefaultInstance();
  PauseNotificationsNotify_default_instance_.get_mutable()->InitAsDefaultInstance();
  RestoreNotificationsNotify_default_instance_.get_mutable()->InitAsDefaultInstance();
  PauseNotificationsReq_default_instance_.get_mutable()->InitAsDefaultInstance();
  RestoreNotificationsReq_default_instance_.get_mutable()->InitAsDefaultInstance();
  TypingNotify_default_instance_.get_mutable()->InitAsDefaultInstance();
  TypingStopNotify_default_instance_.get_mutable()->InitAsDefaultInstance();
  UserOnlineNotify_default_instance_.get_mutable()->InitAsDefaultInstance();
  UserOfflineNotify_default_instance_.get_mutable()->InitAsDefaultInstance();
  UserLastSeenNotify_default_instance_.get_mutable()->InitAsDefaultInstance();
  GroupOnlineNotify_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_weak_2eproto_once_);
void protobuf_InitDefaults_weak_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_weak_2eproto_once_,
                 &protobuf_InitDefaults_weak_2eproto_impl);
}
void protobuf_AddDesc_weak_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_weak_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\nweak.proto\022\006zproto\032\013peers.proto\"S\n\tTyp"
    "ingReq\022\035\n\004peer\030\001 \001(\0132\017.zproto.OutPeer\022\'\n"
    "\013typing_type\030\003 \001(\0162\022.zproto.TypingType\"W"
    "\n\rStopTypingReq\022\035\n\004peer\030\001 \001(\0132\017.zproto.O"
    "utPeer\022\'\n\013typing_type\030\002 \001(\0162\022.zproto.Typ"
    "ingType\"t\n\014SetOnlineReq\022\021\n\tis_online\030\001 \001"
    "(\010\022\017\n\007timeout\030\002 \001(\003\022\'\n\013device_type\030\003 \001(\016"
    "2\022.zproto.DeviceType\022\027\n\017device_category\030"
    "\004 \001(\t\"+\n\030PauseNotificationsNotify\022\017\n\007tim"
    "eout\030\001 \001(\005\"\034\n\032RestoreNotificationsNotify"
    "\"(\n\025PauseNotificationsReq\022\017\n\007timeout\030\001 \001"
    "(\005\"\031\n\027RestoreNotificationsReq\"`\n\014TypingN"
    "otify\022\032\n\004peer\030\001 \001(\0132\014.zproto.Peer\022\013\n\003uid"
    "\030\002 \001(\005\022\'\n\013typing_type\030\003 \001(\0162\022.zproto.Typ"
    "ingType\"d\n\020TypingStopNotify\022\032\n\004peer\030\001 \001("
    "\0132\014.zproto.Peer\022\013\n\003uid\030\002 \001(\005\022\'\n\013typing_t"
    "ype\030\003 \001(\0162\022.zproto.TypingType\"a\n\020UserOnl"
    "ineNotify\022\013\n\003uid\030\001 \001(\005\022\'\n\013device_type\030\002 "
    "\001(\0162\022.zproto.DeviceType\022\027\n\017device_catego"
    "ry\030\003 \001(\t\"b\n\021UserOfflineNotify\022\013\n\003uid\030\001 \001"
    "(\005\022\'\n\013device_type\030\002 \001(\0162\022.zproto.DeviceT"
    "ype\022\027\n\017device_category\030\003 \001(\t\"q\n\022UserLast"
    "SeenNotify\022\013\n\003uid\030\001 \001(\005\022\014\n\004date\030\002 \001(\003\022\'\n"
    "\013device_type\030\003 \001(\0162\022.zproto.DeviceType\022\027"
    "\n\017device_category\030\004 \001(\t\"4\n\021GroupOnlineNo"
    "tify\022\020\n\010group_id\030\001 \001(\005\022\r\n\005count\030\002 \001(\005*\"\n"
    "\nTypingType\022\024\n\020kTypingType_Text\020\000*\304\001\n\nDe"
    "viceType\022\027\n\023kDeviceType_GENERIC\020\000\022\022\n\016kDe"
    "viceType_PC\020\001\022\026\n\022kDeviceType_MOBILE\020\002\022\026\n"
    "\022kDeviceType_TABLET\020\003\022\025\n\021kDeviceType_WAT"
    "CH\020\004\022\026\n\022kDeviceType_MIRROR\020\005\022\023\n\017kDeviceT"
    "ype_CAR\020\006\022\025\n\021kDeviceType_TABLE\020\007B\'\n\027com."
    "zchat.engine.zprotoB\nZProtoWeakH\002b\006proto"
    "3", 1321);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "weak.proto", &protobuf_RegisterTypes);
  ::zproto::protobuf_AddDesc_peers_2eproto();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_weak_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_weak_2eproto_once_);
void protobuf_AddDesc_weak_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_weak_2eproto_once_,
                 &protobuf_AddDesc_weak_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_weak_2eproto {
  StaticDescriptorInitializer_weak_2eproto() {
    protobuf_AddDesc_weak_2eproto();
  }
} static_descriptor_initializer_weak_2eproto_;
const ::google::protobuf::EnumDescriptor* TypingType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TypingType_descriptor_;
}
bool TypingType_IsValid(int value) {
  switch (value) {
    case 0:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* DeviceType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DeviceType_descriptor_;
}
bool DeviceType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TypingReq::kPeerFieldNumber;
const int TypingReq::kTypingTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TypingReq::TypingReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_weak_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.TypingReq)
}

void TypingReq::InitAsDefaultInstance() {
  peer_ = const_cast< ::zproto::OutPeer*>(
      ::zproto::OutPeer::internal_default_instance());
}

TypingReq::TypingReq(const TypingReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.TypingReq)
}

void TypingReq::SharedCtor() {
  peer_ = NULL;
  typing_type_ = 0;
  _cached_size_ = 0;
}

TypingReq::~TypingReq() {
  // @@protoc_insertion_point(destructor:zproto.TypingReq)
  SharedDtor();
}

void TypingReq::SharedDtor() {
  if (this != &TypingReq_default_instance_.get()) {
    delete peer_;
  }
}

void TypingReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TypingReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TypingReq_descriptor_;
}

const TypingReq& TypingReq::default_instance() {
  protobuf_InitDefaults_weak_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<TypingReq> TypingReq_default_instance_;

TypingReq* TypingReq::New(::google::protobuf::Arena* arena) const {
  TypingReq* n = new TypingReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TypingReq::UnsafeMergeFrom(const TypingReq& from) {
  MergeFrom(from);
}
void TypingReq::Swap(TypingReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TypingReq::InternalSwap(TypingReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata TypingReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TypingReq_descriptor_;
  metadata.reflection = TypingReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TypingReq

// optional .zproto.OutPeer peer = 1;
bool TypingReq::has_peer() const {
  return this != internal_default_instance() && peer_ != NULL;
}
void TypingReq::clear_peer() {
  if (GetArenaNoVirtual() == NULL && peer_ != NULL) delete peer_;
  peer_ = NULL;
}
const ::zproto::OutPeer& TypingReq::peer() const {
  // @@protoc_insertion_point(field_get:zproto.TypingReq.peer)
  return peer_ != NULL ? *peer_
                         : *::zproto::OutPeer::internal_default_instance();
}
::zproto::OutPeer* TypingReq::mutable_peer() {
  
  if (peer_ == NULL) {
    peer_ = new ::zproto::OutPeer;
  }
  // @@protoc_insertion_point(field_mutable:zproto.TypingReq.peer)
  return peer_;
}
::zproto::OutPeer* TypingReq::release_peer() {
  // @@protoc_insertion_point(field_release:zproto.TypingReq.peer)
  
  ::zproto::OutPeer* temp = peer_;
  peer_ = NULL;
  return temp;
}
void TypingReq::set_allocated_peer(::zproto::OutPeer* peer) {
  delete peer_;
  peer_ = peer;
  if (peer) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:zproto.TypingReq.peer)
}

// optional .zproto.TypingType typing_type = 3;
void TypingReq::clear_typing_type() {
  typing_type_ = 0;
}
::zproto::TypingType TypingReq::typing_type() const {
  // @@protoc_insertion_point(field_get:zproto.TypingReq.typing_type)
  return static_cast< ::zproto::TypingType >(typing_type_);
}
void TypingReq::set_typing_type(::zproto::TypingType value) {
  
  typing_type_ = value;
  // @@protoc_insertion_point(field_set:zproto.TypingReq.typing_type)
}

inline const TypingReq* TypingReq::internal_default_instance() {
  return &TypingReq_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StopTypingReq::kPeerFieldNumber;
const int StopTypingReq::kTypingTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StopTypingReq::StopTypingReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_weak_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.StopTypingReq)
}

void StopTypingReq::InitAsDefaultInstance() {
  peer_ = const_cast< ::zproto::OutPeer*>(
      ::zproto::OutPeer::internal_default_instance());
}

StopTypingReq::StopTypingReq(const StopTypingReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.StopTypingReq)
}

void StopTypingReq::SharedCtor() {
  peer_ = NULL;
  typing_type_ = 0;
  _cached_size_ = 0;
}

StopTypingReq::~StopTypingReq() {
  // @@protoc_insertion_point(destructor:zproto.StopTypingReq)
  SharedDtor();
}

void StopTypingReq::SharedDtor() {
  if (this != &StopTypingReq_default_instance_.get()) {
    delete peer_;
  }
}

void StopTypingReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StopTypingReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return StopTypingReq_descriptor_;
}

const StopTypingReq& StopTypingReq::default_instance() {
  protobuf_InitDefaults_weak_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<StopTypingReq> StopTypingReq_default_instance_;

StopTypingReq* StopTypingReq::New(::google::protobuf::Arena* arena) const {
  StopTypingReq* n = new StopTypingReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void StopTypingReq::UnsafeMergeFrom(const StopTypingReq& from) {
  MergeFrom(from);
}
void StopTypingReq::Swap(StopTypingReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StopTypingReq::InternalSwap(StopTypingReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata StopTypingReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = StopTypingReq_descriptor_;
  metadata.reflection = StopTypingReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// StopTypingReq

// optional .zproto.OutPeer peer = 1;
bool StopTypingReq::has_peer() const {
  return this != internal_default_instance() && peer_ != NULL;
}
void StopTypingReq::clear_peer() {
  if (GetArenaNoVirtual() == NULL && peer_ != NULL) delete peer_;
  peer_ = NULL;
}
const ::zproto::OutPeer& StopTypingReq::peer() const {
  // @@protoc_insertion_point(field_get:zproto.StopTypingReq.peer)
  return peer_ != NULL ? *peer_
                         : *::zproto::OutPeer::internal_default_instance();
}
::zproto::OutPeer* StopTypingReq::mutable_peer() {
  
  if (peer_ == NULL) {
    peer_ = new ::zproto::OutPeer;
  }
  // @@protoc_insertion_point(field_mutable:zproto.StopTypingReq.peer)
  return peer_;
}
::zproto::OutPeer* StopTypingReq::release_peer() {
  // @@protoc_insertion_point(field_release:zproto.StopTypingReq.peer)
  
  ::zproto::OutPeer* temp = peer_;
  peer_ = NULL;
  return temp;
}
void StopTypingReq::set_allocated_peer(::zproto::OutPeer* peer) {
  delete peer_;
  peer_ = peer;
  if (peer) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:zproto.StopTypingReq.peer)
}

// optional .zproto.TypingType typing_type = 2;
void StopTypingReq::clear_typing_type() {
  typing_type_ = 0;
}
::zproto::TypingType StopTypingReq::typing_type() const {
  // @@protoc_insertion_point(field_get:zproto.StopTypingReq.typing_type)
  return static_cast< ::zproto::TypingType >(typing_type_);
}
void StopTypingReq::set_typing_type(::zproto::TypingType value) {
  
  typing_type_ = value;
  // @@protoc_insertion_point(field_set:zproto.StopTypingReq.typing_type)
}

inline const StopTypingReq* StopTypingReq::internal_default_instance() {
  return &StopTypingReq_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SetOnlineReq::kIsOnlineFieldNumber;
const int SetOnlineReq::kTimeoutFieldNumber;
const int SetOnlineReq::kDeviceTypeFieldNumber;
const int SetOnlineReq::kDeviceCategoryFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SetOnlineReq::SetOnlineReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_weak_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.SetOnlineReq)
}

void SetOnlineReq::InitAsDefaultInstance() {
}

SetOnlineReq::SetOnlineReq(const SetOnlineReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.SetOnlineReq)
}

void SetOnlineReq::SharedCtor() {
  device_category_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&timeout_, 0, reinterpret_cast<char*>(&device_type_) -
    reinterpret_cast<char*>(&timeout_) + sizeof(device_type_));
  _cached_size_ = 0;
}

SetOnlineReq::~SetOnlineReq() {
  // @@protoc_insertion_point(destructor:zproto.SetOnlineReq)
  SharedDtor();
}

void SetOnlineReq::SharedDtor() {
  device_category_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SetOnlineReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SetOnlineReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SetOnlineReq_descriptor_;
}

const SetOnlineReq& SetOnlineReq::default_instance() {
  protobuf_InitDefaults_weak_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<SetOnlineReq> SetOnlineReq_default_instance_;

SetOnlineReq* SetOnlineReq::New(::google::protobuf::Arena* arena) const {
  SetOnlineReq* n = new SetOnlineReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SetOnlineReq::UnsafeMergeFrom(const SetOnlineReq& from) {
  MergeFrom(from);
}
void SetOnlineReq::Swap(SetOnlineReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SetOnlineReq::InternalSwap(SetOnlineReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata SetOnlineReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SetOnlineReq_descriptor_;
  metadata.reflection = SetOnlineReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SetOnlineReq

// optional bool is_online = 1;
void SetOnlineReq::clear_is_online() {
  is_online_ = false;
}
bool SetOnlineReq::is_online() const {
  // @@protoc_insertion_point(field_get:zproto.SetOnlineReq.is_online)
  return is_online_;
}
void SetOnlineReq::set_is_online(bool value) {
  
  is_online_ = value;
  // @@protoc_insertion_point(field_set:zproto.SetOnlineReq.is_online)
}

// optional int64 timeout = 2;
void SetOnlineReq::clear_timeout() {
  timeout_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 SetOnlineReq::timeout() const {
  // @@protoc_insertion_point(field_get:zproto.SetOnlineReq.timeout)
  return timeout_;
}
void SetOnlineReq::set_timeout(::google::protobuf::int64 value) {
  
  timeout_ = value;
  // @@protoc_insertion_point(field_set:zproto.SetOnlineReq.timeout)
}

// optional .zproto.DeviceType device_type = 3;
void SetOnlineReq::clear_device_type() {
  device_type_ = 0;
}
::zproto::DeviceType SetOnlineReq::device_type() const {
  // @@protoc_insertion_point(field_get:zproto.SetOnlineReq.device_type)
  return static_cast< ::zproto::DeviceType >(device_type_);
}
void SetOnlineReq::set_device_type(::zproto::DeviceType value) {
  
  device_type_ = value;
  // @@protoc_insertion_point(field_set:zproto.SetOnlineReq.device_type)
}

// optional string device_category = 4;
void SetOnlineReq::clear_device_category() {
  device_category_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& SetOnlineReq::device_category() const {
  // @@protoc_insertion_point(field_get:zproto.SetOnlineReq.device_category)
  return device_category_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void SetOnlineReq::set_device_category(const ::std::string& value) {
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.SetOnlineReq.device_category)
}
void SetOnlineReq::set_device_category(const char* value) {
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.SetOnlineReq.device_category)
}
void SetOnlineReq::set_device_category(const char* value, size_t size) {
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.SetOnlineReq.device_category)
}
::std::string* SetOnlineReq::mutable_device_category() {
  
  // @@protoc_insertion_point(field_mutable:zproto.SetOnlineReq.device_category)
  return device_category_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* SetOnlineReq::release_device_category() {
  // @@protoc_insertion_point(field_release:zproto.SetOnlineReq.device_category)
  
  return device_category_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void SetOnlineReq::set_allocated_device_category(::std::string* device_category) {
  if (device_category != NULL) {
    
  } else {
    
  }
  device_category_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), device_category);
  // @@protoc_insertion_point(field_set_allocated:zproto.SetOnlineReq.device_category)
}

inline const SetOnlineReq* SetOnlineReq::internal_default_instance() {
  return &SetOnlineReq_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PauseNotificationsNotify::kTimeoutFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PauseNotificationsNotify::PauseNotificationsNotify()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_weak_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.PauseNotificationsNotify)
}

void PauseNotificationsNotify::InitAsDefaultInstance() {
}

PauseNotificationsNotify::PauseNotificationsNotify(const PauseNotificationsNotify& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.PauseNotificationsNotify)
}

void PauseNotificationsNotify::SharedCtor() {
  timeout_ = 0;
  _cached_size_ = 0;
}

PauseNotificationsNotify::~PauseNotificationsNotify() {
  // @@protoc_insertion_point(destructor:zproto.PauseNotificationsNotify)
  SharedDtor();
}

void PauseNotificationsNotify::SharedDtor() {
}

void PauseNotificationsNotify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PauseNotificationsNotify::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PauseNotificationsNotify_descriptor_;
}

const PauseNotificationsNotify& PauseNotificationsNotify::default_instance() {
  protobuf_InitDefaults_weak_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<PauseNotificationsNotify> PauseNotificationsNotify_default_instance_;

PauseNotificationsNotify* PauseNotificationsNotify::New(::google::protobuf::Arena* arena) const {
  PauseNotificationsNotify* n = new PauseNotificationsNotify;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PauseNotificationsNotify::UnsafeMergeFrom(const PauseNotificationsNotify& from) {
  MergeFrom(from);
}
void PauseNotificationsNotify::Swap(PauseNotificationsNotify* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PauseNotificationsNotify::InternalSwap(PauseNotificationsNotify* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata PauseNotificationsNotify::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PauseNotificationsNotify_descriptor_;
  metadata.reflection = PauseNotificationsNotify_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PauseNotificationsNotify

// optional int32 timeout = 1;
void PauseNotificationsNotify::clear_timeout() {
  timeout_ = 0;
}
::google::protobuf::int32 PauseNotificationsNotify::timeout() const {
  // @@protoc_insertion_point(field_get:zproto.PauseNotificationsNotify.timeout)
  return timeout_;
}
void PauseNotificationsNotify::set_timeout(::google::protobuf::int32 value) {
  
  timeout_ = value;
  // @@protoc_insertion_point(field_set:zproto.PauseNotificationsNotify.timeout)
}

inline const PauseNotificationsNotify* PauseNotificationsNotify::internal_default_instance() {
  return &PauseNotificationsNotify_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RestoreNotificationsNotify::RestoreNotificationsNotify()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_weak_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.RestoreNotificationsNotify)
}

void RestoreNotificationsNotify::InitAsDefaultInstance() {
}

RestoreNotificationsNotify::RestoreNotificationsNotify(const RestoreNotificationsNotify& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.RestoreNotificationsNotify)
}

void RestoreNotificationsNotify::SharedCtor() {
  _cached_size_ = 0;
}

RestoreNotificationsNotify::~RestoreNotificationsNotify() {
  // @@protoc_insertion_point(destructor:zproto.RestoreNotificationsNotify)
  SharedDtor();
}

void RestoreNotificationsNotify::SharedDtor() {
}

void RestoreNotificationsNotify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RestoreNotificationsNotify::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RestoreNotificationsNotify_descriptor_;
}

const RestoreNotificationsNotify& RestoreNotificationsNotify::default_instance() {
  protobuf_InitDefaults_weak_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<RestoreNotificationsNotify> RestoreNotificationsNotify_default_instance_;

RestoreNotificationsNotify* RestoreNotificationsNotify::New(::google::protobuf::Arena* arena) const {
  RestoreNotificationsNotify* n = new RestoreNotificationsNotify;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RestoreNotificationsNotify::UnsafeMergeFrom(const RestoreNotificationsNotify& from) {
  MergeFrom(from);
}
void RestoreNotificationsNotify::Swap(RestoreNotificationsNotify* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RestoreNotificationsNotify::InternalSwap(RestoreNotificationsNotify* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata RestoreNotificationsNotify::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RestoreNotificationsNotify_descriptor_;
  metadata.reflection = RestoreNotificationsNotify_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RestoreNotificationsNotify

inline const RestoreNotificationsNotify* RestoreNotificationsNotify::internal_default_instance() {
  return &RestoreNotificationsNotify_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PauseNotificationsReq::kTimeoutFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PauseNotificationsReq::PauseNotificationsReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_weak_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.PauseNotificationsReq)
}

void PauseNotificationsReq::InitAsDefaultInstance() {
}

PauseNotificationsReq::PauseNotificationsReq(const PauseNotificationsReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.PauseNotificationsReq)
}

void PauseNotificationsReq::SharedCtor() {
  timeout_ = 0;
  _cached_size_ = 0;
}

PauseNotificationsReq::~PauseNotificationsReq() {
  // @@protoc_insertion_point(destructor:zproto.PauseNotificationsReq)
  SharedDtor();
}

void PauseNotificationsReq::SharedDtor() {
}

void PauseNotificationsReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PauseNotificationsReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PauseNotificationsReq_descriptor_;
}

const PauseNotificationsReq& PauseNotificationsReq::default_instance() {
  protobuf_InitDefaults_weak_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<PauseNotificationsReq> PauseNotificationsReq_default_instance_;

PauseNotificationsReq* PauseNotificationsReq::New(::google::protobuf::Arena* arena) const {
  PauseNotificationsReq* n = new PauseNotificationsReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PauseNotificationsReq::UnsafeMergeFrom(const PauseNotificationsReq& from) {
  MergeFrom(from);
}
void PauseNotificationsReq::Swap(PauseNotificationsReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PauseNotificationsReq::InternalSwap(PauseNotificationsReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata PauseNotificationsReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PauseNotificationsReq_descriptor_;
  metadata.reflection = PauseNotificationsReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PauseNotificationsReq

// optional int32 timeout = 1;
void PauseNotificationsReq::clear_timeout() {
  timeout_ = 0;
}
::google::protobuf::int32 PauseNotificationsReq::timeout() const {
  // @@protoc_insertion_point(field_get:zproto.PauseNotificationsReq.timeout)
  return timeout_;
}
void PauseNotificationsReq::set_timeout(::google::protobuf::int32 value) {
  
  timeout_ = value;
  // @@protoc_insertion_point(field_set:zproto.PauseNotificationsReq.timeout)
}

inline const PauseNotificationsReq* PauseNotificationsReq::internal_default_instance() {
  return &PauseNotificationsReq_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RestoreNotificationsReq::RestoreNotificationsReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_weak_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.RestoreNotificationsReq)
}

void RestoreNotificationsReq::InitAsDefaultInstance() {
}

RestoreNotificationsReq::RestoreNotificationsReq(const RestoreNotificationsReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.RestoreNotificationsReq)
}

void RestoreNotificationsReq::SharedCtor() {
  _cached_size_ = 0;
}

RestoreNotificationsReq::~RestoreNotificationsReq() {
  // @@protoc_insertion_point(destructor:zproto.RestoreNotificationsReq)
  SharedDtor();
}

void RestoreNotificationsReq::SharedDtor() {
}

void RestoreNotificationsReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RestoreNotificationsReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RestoreNotificationsReq_descriptor_;
}

const RestoreNotificationsReq& RestoreNotificationsReq::default_instance() {
  protobuf_InitDefaults_weak_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<RestoreNotificationsReq> RestoreNotificationsReq_default_instance_;

RestoreNotificationsReq* RestoreNotificationsReq::New(::google::protobuf::Arena* arena) const {
  RestoreNotificationsReq* n = new RestoreNotificationsReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RestoreNotificationsReq::UnsafeMergeFrom(const RestoreNotificationsReq& from) {
  MergeFrom(from);
}
void RestoreNotificationsReq::Swap(RestoreNotificationsReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RestoreNotificationsReq::InternalSwap(RestoreNotificationsReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata RestoreNotificationsReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RestoreNotificationsReq_descriptor_;
  metadata.reflection = RestoreNotificationsReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RestoreNotificationsReq

inline const RestoreNotificationsReq* RestoreNotificationsReq::internal_default_instance() {
  return &RestoreNotificationsReq_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TypingNotify::kPeerFieldNumber;
const int TypingNotify::kUidFieldNumber;
const int TypingNotify::kTypingTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TypingNotify::TypingNotify()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_weak_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.TypingNotify)
}

void TypingNotify::InitAsDefaultInstance() {
  peer_ = const_cast< ::zproto::Peer*>(
      ::zproto::Peer::internal_default_instance());
}

TypingNotify::TypingNotify(const TypingNotify& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.TypingNotify)
}

void TypingNotify::SharedCtor() {
  peer_ = NULL;
  ::memset(&uid_, 0, reinterpret_cast<char*>(&typing_type_) -
    reinterpret_cast<char*>(&uid_) + sizeof(typing_type_));
  _cached_size_ = 0;
}

TypingNotify::~TypingNotify() {
  // @@protoc_insertion_point(destructor:zproto.TypingNotify)
  SharedDtor();
}

void TypingNotify::SharedDtor() {
  if (this != &TypingNotify_default_instance_.get()) {
    delete peer_;
  }
}

void TypingNotify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TypingNotify::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TypingNotify_descriptor_;
}

const TypingNotify& TypingNotify::default_instance() {
  protobuf_InitDefaults_weak_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<TypingNotify> TypingNotify_default_instance_;

TypingNotify* TypingNotify::New(::google::protobuf::Arena* arena) const {
  TypingNotify* n = new TypingNotify;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TypingNotify::UnsafeMergeFrom(const TypingNotify& from) {
  MergeFrom(from);
}
void TypingNotify::Swap(TypingNotify* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TypingNotify::InternalSwap(TypingNotify* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata TypingNotify::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TypingNotify_descriptor_;
  metadata.reflection = TypingNotify_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TypingNotify

// optional .zproto.Peer peer = 1;
bool TypingNotify::has_peer() const {
  return this != internal_default_instance() && peer_ != NULL;
}
void TypingNotify::clear_peer() {
  if (GetArenaNoVirtual() == NULL && peer_ != NULL) delete peer_;
  peer_ = NULL;
}
const ::zproto::Peer& TypingNotify::peer() const {
  // @@protoc_insertion_point(field_get:zproto.TypingNotify.peer)
  return peer_ != NULL ? *peer_
                         : *::zproto::Peer::internal_default_instance();
}
::zproto::Peer* TypingNotify::mutable_peer() {
  
  if (peer_ == NULL) {
    peer_ = new ::zproto::Peer;
  }
  // @@protoc_insertion_point(field_mutable:zproto.TypingNotify.peer)
  return peer_;
}
::zproto::Peer* TypingNotify::release_peer() {
  // @@protoc_insertion_point(field_release:zproto.TypingNotify.peer)
  
  ::zproto::Peer* temp = peer_;
  peer_ = NULL;
  return temp;
}
void TypingNotify::set_allocated_peer(::zproto::Peer* peer) {
  delete peer_;
  peer_ = peer;
  if (peer) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:zproto.TypingNotify.peer)
}

// optional int32 uid = 2;
void TypingNotify::clear_uid() {
  uid_ = 0;
}
::google::protobuf::int32 TypingNotify::uid() const {
  // @@protoc_insertion_point(field_get:zproto.TypingNotify.uid)
  return uid_;
}
void TypingNotify::set_uid(::google::protobuf::int32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:zproto.TypingNotify.uid)
}

// optional .zproto.TypingType typing_type = 3;
void TypingNotify::clear_typing_type() {
  typing_type_ = 0;
}
::zproto::TypingType TypingNotify::typing_type() const {
  // @@protoc_insertion_point(field_get:zproto.TypingNotify.typing_type)
  return static_cast< ::zproto::TypingType >(typing_type_);
}
void TypingNotify::set_typing_type(::zproto::TypingType value) {
  
  typing_type_ = value;
  // @@protoc_insertion_point(field_set:zproto.TypingNotify.typing_type)
}

inline const TypingNotify* TypingNotify::internal_default_instance() {
  return &TypingNotify_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TypingStopNotify::kPeerFieldNumber;
const int TypingStopNotify::kUidFieldNumber;
const int TypingStopNotify::kTypingTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TypingStopNotify::TypingStopNotify()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_weak_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.TypingStopNotify)
}

void TypingStopNotify::InitAsDefaultInstance() {
  peer_ = const_cast< ::zproto::Peer*>(
      ::zproto::Peer::internal_default_instance());
}

TypingStopNotify::TypingStopNotify(const TypingStopNotify& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.TypingStopNotify)
}

void TypingStopNotify::SharedCtor() {
  peer_ = NULL;
  ::memset(&uid_, 0, reinterpret_cast<char*>(&typing_type_) -
    reinterpret_cast<char*>(&uid_) + sizeof(typing_type_));
  _cached_size_ = 0;
}

TypingStopNotify::~TypingStopNotify() {
  // @@protoc_insertion_point(destructor:zproto.TypingStopNotify)
  SharedDtor();
}

void TypingStopNotify::SharedDtor() {
  if (this != &TypingStopNotify_default_instance_.get()) {
    delete peer_;
  }
}

void TypingStopNotify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TypingStopNotify::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TypingStopNotify_descriptor_;
}

const TypingStopNotify& TypingStopNotify::default_instance() {
  protobuf_InitDefaults_weak_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<TypingStopNotify> TypingStopNotify_default_instance_;

TypingStopNotify* TypingStopNotify::New(::google::protobuf::Arena* arena) const {
  TypingStopNotify* n = new TypingStopNotify;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TypingStopNotify::UnsafeMergeFrom(const TypingStopNotify& from) {
  MergeFrom(from);
}
void TypingStopNotify::Swap(TypingStopNotify* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TypingStopNotify::InternalSwap(TypingStopNotify* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata TypingStopNotify::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TypingStopNotify_descriptor_;
  metadata.reflection = TypingStopNotify_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TypingStopNotify

// optional .zproto.Peer peer = 1;
bool TypingStopNotify::has_peer() const {
  return this != internal_default_instance() && peer_ != NULL;
}
void TypingStopNotify::clear_peer() {
  if (GetArenaNoVirtual() == NULL && peer_ != NULL) delete peer_;
  peer_ = NULL;
}
const ::zproto::Peer& TypingStopNotify::peer() const {
  // @@protoc_insertion_point(field_get:zproto.TypingStopNotify.peer)
  return peer_ != NULL ? *peer_
                         : *::zproto::Peer::internal_default_instance();
}
::zproto::Peer* TypingStopNotify::mutable_peer() {
  
  if (peer_ == NULL) {
    peer_ = new ::zproto::Peer;
  }
  // @@protoc_insertion_point(field_mutable:zproto.TypingStopNotify.peer)
  return peer_;
}
::zproto::Peer* TypingStopNotify::release_peer() {
  // @@protoc_insertion_point(field_release:zproto.TypingStopNotify.peer)
  
  ::zproto::Peer* temp = peer_;
  peer_ = NULL;
  return temp;
}
void TypingStopNotify::set_allocated_peer(::zproto::Peer* peer) {
  delete peer_;
  peer_ = peer;
  if (peer) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:zproto.TypingStopNotify.peer)
}

// optional int32 uid = 2;
void TypingStopNotify::clear_uid() {
  uid_ = 0;
}
::google::protobuf::int32 TypingStopNotify::uid() const {
  // @@protoc_insertion_point(field_get:zproto.TypingStopNotify.uid)
  return uid_;
}
void TypingStopNotify::set_uid(::google::protobuf::int32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:zproto.TypingStopNotify.uid)
}

// optional .zproto.TypingType typing_type = 3;
void TypingStopNotify::clear_typing_type() {
  typing_type_ = 0;
}
::zproto::TypingType TypingStopNotify::typing_type() const {
  // @@protoc_insertion_point(field_get:zproto.TypingStopNotify.typing_type)
  return static_cast< ::zproto::TypingType >(typing_type_);
}
void TypingStopNotify::set_typing_type(::zproto::TypingType value) {
  
  typing_type_ = value;
  // @@protoc_insertion_point(field_set:zproto.TypingStopNotify.typing_type)
}

inline const TypingStopNotify* TypingStopNotify::internal_default_instance() {
  return &TypingStopNotify_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UserOnlineNotify::kUidFieldNumber;
const int UserOnlineNotify::kDeviceTypeFieldNumber;
const int UserOnlineNotify::kDeviceCategoryFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UserOnlineNotify::UserOnlineNotify()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_weak_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.UserOnlineNotify)
}

void UserOnlineNotify::InitAsDefaultInstance() {
}

UserOnlineNotify::UserOnlineNotify(const UserOnlineNotify& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.UserOnlineNotify)
}

void UserOnlineNotify::SharedCtor() {
  device_category_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&uid_, 0, reinterpret_cast<char*>(&device_type_) -
    reinterpret_cast<char*>(&uid_) + sizeof(device_type_));
  _cached_size_ = 0;
}

UserOnlineNotify::~UserOnlineNotify() {
  // @@protoc_insertion_point(destructor:zproto.UserOnlineNotify)
  SharedDtor();
}

void UserOnlineNotify::SharedDtor() {
  device_category_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void UserOnlineNotify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UserOnlineNotify::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UserOnlineNotify_descriptor_;
}

const UserOnlineNotify& UserOnlineNotify::default_instance() {
  protobuf_InitDefaults_weak_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<UserOnlineNotify> UserOnlineNotify_default_instance_;

UserOnlineNotify* UserOnlineNotify::New(::google::protobuf::Arena* arena) const {
  UserOnlineNotify* n = new UserOnlineNotify;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void UserOnlineNotify::UnsafeMergeFrom(const UserOnlineNotify& from) {
  MergeFrom(from);
}
void UserOnlineNotify::Swap(UserOnlineNotify* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UserOnlineNotify::InternalSwap(UserOnlineNotify* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata UserOnlineNotify::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = UserOnlineNotify_descriptor_;
  metadata.reflection = UserOnlineNotify_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// UserOnlineNotify

// optional int32 uid = 1;
void UserOnlineNotify::clear_uid() {
  uid_ = 0;
}
::google::protobuf::int32 UserOnlineNotify::uid() const {
  // @@protoc_insertion_point(field_get:zproto.UserOnlineNotify.uid)
  return uid_;
}
void UserOnlineNotify::set_uid(::google::protobuf::int32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:zproto.UserOnlineNotify.uid)
}

// optional .zproto.DeviceType device_type = 2;
void UserOnlineNotify::clear_device_type() {
  device_type_ = 0;
}
::zproto::DeviceType UserOnlineNotify::device_type() const {
  // @@protoc_insertion_point(field_get:zproto.UserOnlineNotify.device_type)
  return static_cast< ::zproto::DeviceType >(device_type_);
}
void UserOnlineNotify::set_device_type(::zproto::DeviceType value) {
  
  device_type_ = value;
  // @@protoc_insertion_point(field_set:zproto.UserOnlineNotify.device_type)
}

// optional string device_category = 3;
void UserOnlineNotify::clear_device_category() {
  device_category_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& UserOnlineNotify::device_category() const {
  // @@protoc_insertion_point(field_get:zproto.UserOnlineNotify.device_category)
  return device_category_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void UserOnlineNotify::set_device_category(const ::std::string& value) {
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.UserOnlineNotify.device_category)
}
void UserOnlineNotify::set_device_category(const char* value) {
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.UserOnlineNotify.device_category)
}
void UserOnlineNotify::set_device_category(const char* value, size_t size) {
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.UserOnlineNotify.device_category)
}
::std::string* UserOnlineNotify::mutable_device_category() {
  
  // @@protoc_insertion_point(field_mutable:zproto.UserOnlineNotify.device_category)
  return device_category_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* UserOnlineNotify::release_device_category() {
  // @@protoc_insertion_point(field_release:zproto.UserOnlineNotify.device_category)
  
  return device_category_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void UserOnlineNotify::set_allocated_device_category(::std::string* device_category) {
  if (device_category != NULL) {
    
  } else {
    
  }
  device_category_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), device_category);
  // @@protoc_insertion_point(field_set_allocated:zproto.UserOnlineNotify.device_category)
}

inline const UserOnlineNotify* UserOnlineNotify::internal_default_instance() {
  return &UserOnlineNotify_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UserOfflineNotify::kUidFieldNumber;
const int UserOfflineNotify::kDeviceTypeFieldNumber;
const int UserOfflineNotify::kDeviceCategoryFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UserOfflineNotify::UserOfflineNotify()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_weak_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.UserOfflineNotify)
}

void UserOfflineNotify::InitAsDefaultInstance() {
}

UserOfflineNotify::UserOfflineNotify(const UserOfflineNotify& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.UserOfflineNotify)
}

void UserOfflineNotify::SharedCtor() {
  device_category_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&uid_, 0, reinterpret_cast<char*>(&device_type_) -
    reinterpret_cast<char*>(&uid_) + sizeof(device_type_));
  _cached_size_ = 0;
}

UserOfflineNotify::~UserOfflineNotify() {
  // @@protoc_insertion_point(destructor:zproto.UserOfflineNotify)
  SharedDtor();
}

void UserOfflineNotify::SharedDtor() {
  device_category_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void UserOfflineNotify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UserOfflineNotify::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UserOfflineNotify_descriptor_;
}

const UserOfflineNotify& UserOfflineNotify::default_instance() {
  protobuf_InitDefaults_weak_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<UserOfflineNotify> UserOfflineNotify_default_instance_;

UserOfflineNotify* UserOfflineNotify::New(::google::protobuf::Arena* arena) const {
  UserOfflineNotify* n = new UserOfflineNotify;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void UserOfflineNotify::UnsafeMergeFrom(const UserOfflineNotify& from) {
  MergeFrom(from);
}
void UserOfflineNotify::Swap(UserOfflineNotify* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UserOfflineNotify::InternalSwap(UserOfflineNotify* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata UserOfflineNotify::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = UserOfflineNotify_descriptor_;
  metadata.reflection = UserOfflineNotify_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// UserOfflineNotify

// optional int32 uid = 1;
void UserOfflineNotify::clear_uid() {
  uid_ = 0;
}
::google::protobuf::int32 UserOfflineNotify::uid() const {
  // @@protoc_insertion_point(field_get:zproto.UserOfflineNotify.uid)
  return uid_;
}
void UserOfflineNotify::set_uid(::google::protobuf::int32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:zproto.UserOfflineNotify.uid)
}

// optional .zproto.DeviceType device_type = 2;
void UserOfflineNotify::clear_device_type() {
  device_type_ = 0;
}
::zproto::DeviceType UserOfflineNotify::device_type() const {
  // @@protoc_insertion_point(field_get:zproto.UserOfflineNotify.device_type)
  return static_cast< ::zproto::DeviceType >(device_type_);
}
void UserOfflineNotify::set_device_type(::zproto::DeviceType value) {
  
  device_type_ = value;
  // @@protoc_insertion_point(field_set:zproto.UserOfflineNotify.device_type)
}

// optional string device_category = 3;
void UserOfflineNotify::clear_device_category() {
  device_category_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& UserOfflineNotify::device_category() const {
  // @@protoc_insertion_point(field_get:zproto.UserOfflineNotify.device_category)
  return device_category_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void UserOfflineNotify::set_device_category(const ::std::string& value) {
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.UserOfflineNotify.device_category)
}
void UserOfflineNotify::set_device_category(const char* value) {
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.UserOfflineNotify.device_category)
}
void UserOfflineNotify::set_device_category(const char* value, size_t size) {
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.UserOfflineNotify.device_category)
}
::std::string* UserOfflineNotify::mutable_device_category() {
  
  // @@protoc_insertion_point(field_mutable:zproto.UserOfflineNotify.device_category)
  return device_category_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* UserOfflineNotify::release_device_category() {
  // @@protoc_insertion_point(field_release:zproto.UserOfflineNotify.device_category)
  
  return device_category_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void UserOfflineNotify::set_allocated_device_category(::std::string* device_category) {
  if (device_category != NULL) {
    
  } else {
    
  }
  device_category_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), device_category);
  // @@protoc_insertion_point(field_set_allocated:zproto.UserOfflineNotify.device_category)
}

inline const UserOfflineNotify* UserOfflineNotify::internal_default_instance() {
  return &UserOfflineNotify_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UserLastSeenNotify::kUidFieldNumber;
const int UserLastSeenNotify::kDateFieldNumber;
const int UserLastSeenNotify::kDeviceTypeFieldNumber;
const int UserLastSeenNotify::kDeviceCategoryFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UserLastSeenNotify::UserLastSeenNotify()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_weak_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.UserLastSeenNotify)
}

void UserLastSeenNotify::InitAsDefaultInstance() {
}

UserLastSeenNotify::UserLastSeenNotify(const UserLastSeenNotify& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.UserLastSeenNotify)
}

void UserLastSeenNotify::SharedCtor() {
  device_category_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&date_, 0, reinterpret_cast<char*>(&device_type_) -
    reinterpret_cast<char*>(&date_) + sizeof(device_type_));
  _cached_size_ = 0;
}

UserLastSeenNotify::~UserLastSeenNotify() {
  // @@protoc_insertion_point(destructor:zproto.UserLastSeenNotify)
  SharedDtor();
}

void UserLastSeenNotify::SharedDtor() {
  device_category_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void UserLastSeenNotify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UserLastSeenNotify::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UserLastSeenNotify_descriptor_;
}

const UserLastSeenNotify& UserLastSeenNotify::default_instance() {
  protobuf_InitDefaults_weak_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<UserLastSeenNotify> UserLastSeenNotify_default_instance_;

UserLastSeenNotify* UserLastSeenNotify::New(::google::protobuf::Arena* arena) const {
  UserLastSeenNotify* n = new UserLastSeenNotify;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void UserLastSeenNotify::UnsafeMergeFrom(const UserLastSeenNotify& from) {
  MergeFrom(from);
}
void UserLastSeenNotify::Swap(UserLastSeenNotify* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UserLastSeenNotify::InternalSwap(UserLastSeenNotify* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata UserLastSeenNotify::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = UserLastSeenNotify_descriptor_;
  metadata.reflection = UserLastSeenNotify_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// UserLastSeenNotify

// optional int32 uid = 1;
void UserLastSeenNotify::clear_uid() {
  uid_ = 0;
}
::google::protobuf::int32 UserLastSeenNotify::uid() const {
  // @@protoc_insertion_point(field_get:zproto.UserLastSeenNotify.uid)
  return uid_;
}
void UserLastSeenNotify::set_uid(::google::protobuf::int32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:zproto.UserLastSeenNotify.uid)
}

// optional int64 date = 2;
void UserLastSeenNotify::clear_date() {
  date_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 UserLastSeenNotify::date() const {
  // @@protoc_insertion_point(field_get:zproto.UserLastSeenNotify.date)
  return date_;
}
void UserLastSeenNotify::set_date(::google::protobuf::int64 value) {
  
  date_ = value;
  // @@protoc_insertion_point(field_set:zproto.UserLastSeenNotify.date)
}

// optional .zproto.DeviceType device_type = 3;
void UserLastSeenNotify::clear_device_type() {
  device_type_ = 0;
}
::zproto::DeviceType UserLastSeenNotify::device_type() const {
  // @@protoc_insertion_point(field_get:zproto.UserLastSeenNotify.device_type)
  return static_cast< ::zproto::DeviceType >(device_type_);
}
void UserLastSeenNotify::set_device_type(::zproto::DeviceType value) {
  
  device_type_ = value;
  // @@protoc_insertion_point(field_set:zproto.UserLastSeenNotify.device_type)
}

// optional string device_category = 4;
void UserLastSeenNotify::clear_device_category() {
  device_category_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& UserLastSeenNotify::device_category() const {
  // @@protoc_insertion_point(field_get:zproto.UserLastSeenNotify.device_category)
  return device_category_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void UserLastSeenNotify::set_device_category(const ::std::string& value) {
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.UserLastSeenNotify.device_category)
}
void UserLastSeenNotify::set_device_category(const char* value) {
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.UserLastSeenNotify.device_category)
}
void UserLastSeenNotify::set_device_category(const char* value, size_t size) {
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.UserLastSeenNotify.device_category)
}
::std::string* UserLastSeenNotify::mutable_device_category() {
  
  // @@protoc_insertion_point(field_mutable:zproto.UserLastSeenNotify.device_category)
  return device_category_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* UserLastSeenNotify::release_device_category() {
  // @@protoc_insertion_point(field_release:zproto.UserLastSeenNotify.device_category)
  
  return device_category_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void UserLastSeenNotify::set_allocated_device_category(::std::string* device_category) {
  if (device_category != NULL) {
    
  } else {
    
  }
  device_category_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), device_category);
  // @@protoc_insertion_point(field_set_allocated:zproto.UserLastSeenNotify.device_category)
}

inline const UserLastSeenNotify* UserLastSeenNotify::internal_default_instance() {
  return &UserLastSeenNotify_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GroupOnlineNotify::kGroupIdFieldNumber;
const int GroupOnlineNotify::kCountFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GroupOnlineNotify::GroupOnlineNotify()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_weak_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.GroupOnlineNotify)
}

void GroupOnlineNotify::InitAsDefaultInstance() {
}

GroupOnlineNotify::GroupOnlineNotify(const GroupOnlineNotify& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.GroupOnlineNotify)
}

void GroupOnlineNotify::SharedCtor() {
  ::memset(&group_id_, 0, reinterpret_cast<char*>(&count_) -
    reinterpret_cast<char*>(&group_id_) + sizeof(count_));
  _cached_size_ = 0;
}

GroupOnlineNotify::~GroupOnlineNotify() {
  // @@protoc_insertion_point(destructor:zproto.GroupOnlineNotify)
  SharedDtor();
}

void GroupOnlineNotify::SharedDtor() {
}

void GroupOnlineNotify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GroupOnlineNotify::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GroupOnlineNotify_descriptor_;
}

const GroupOnlineNotify& GroupOnlineNotify::default_instance() {
  protobuf_InitDefaults_weak_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<GroupOnlineNotify> GroupOnlineNotify_default_instance_;

GroupOnlineNotify* GroupOnlineNotify::New(::google::protobuf::Arena* arena) const {
  GroupOnlineNotify* n = new GroupOnlineNotify;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GroupOnlineNotify::UnsafeMergeFrom(const GroupOnlineNotify& from) {
  MergeFrom(from);
}
void GroupOnlineNotify::Swap(GroupOnlineNotify* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GroupOnlineNotify::InternalSwap(GroupOnlineNotify* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata GroupOnlineNotify::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GroupOnlineNotify_descriptor_;
  metadata.reflection = GroupOnlineNotify_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GroupOnlineNotify

// optional int32 group_id = 1;
void GroupOnlineNotify::clear_group_id() {
  group_id_ = 0;
}
::google::protobuf::int32 GroupOnlineNotify::group_id() const {
  // @@protoc_insertion_point(field_get:zproto.GroupOnlineNotify.group_id)
  return group_id_;
}
void GroupOnlineNotify::set_group_id(::google::protobuf::int32 value) {
  
  group_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.GroupOnlineNotify.group_id)
}

// optional int32 count = 2;
void GroupOnlineNotify::clear_count() {
  count_ = 0;
}
::google::protobuf::int32 GroupOnlineNotify::count() const {
  // @@protoc_insertion_point(field_get:zproto.GroupOnlineNotify.count)
  return count_;
}
void GroupOnlineNotify::set_count(::google::protobuf::int32 value) {
  
  count_ = value;
  // @@protoc_insertion_point(field_set:zproto.GroupOnlineNotify.count)
}

inline const GroupOnlineNotify* GroupOnlineNotify::internal_default_instance() {
  return &GroupOnlineNotify_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace zproto

// @@protoc_insertion_point(global_scope)
